# Grid: flap al-am, 30% removed, prompt+generated calibration, pruned for all ten directions. Written by scripts/grid.py configs.
name: alma-7b-flap30-gen-multi
method: flap
allocation: al-am
sparsity: 0.3
calibration: data/calibration/multi-10dir-generated
calibration_text: prompt+generated
model_name_or_path: /scratch-shared/scur0560/models/alma-7b-bf16
dtype: bfloat16
batch_size: 4
max_length: 768
seed: 1234
