# Grid: flap al-am, 30% removed, prompt+generated calibration, pruned for is-en. Written by scripts/grid.py configs.
name: alma-7b-flap30-gen-dir-is-en
method: flap
allocation: al-am
sparsity: 0.3
calibration: data/calibration/dir-is-en-1280-generated
calibration_text: prompt+generated
directions: [is-en]
model_name_or_path: /scratch-shared/scur0560/models/alma-7b-bf16
dtype: bfloat16
batch_size: 4
max_length: 768
seed: 1234
