# Grid: slimgpt log-increase, 30% removed, prompt+target calibration, pruned for is-en. Written by scripts/grid.py configs.
name: alma-7b-slimgpt30-ref-dir-is-en
method: slimgpt
allocation: log-increase
sparsity: 0.3
calibration: data/calibration/dir-is-en-1280
calibration_text: prompt+target
directions: [is-en]
model_name_or_path: /scratch-shared/scur0560/models/alma-7b-bf16
dtype: bfloat16
batch_size: 4
max_length: 768
seed: 1234
