# Grid: flap al-am, 40% removed, prompt+target calibration, pruned for all ten directions. Written by scripts/grid.py configs.
name: alma-7b-flap40-ref-multi
method: flap
allocation: al-am
sparsity: 0.4
calibration: data/calibration/multi-10dir
calibration_text: prompt+target
model_name_or_path: /scratch-shared/scur0560/models/alma-7b-bf16
dtype: bfloat16
batch_size: 4
max_length: 768
seed: 1234
