# LoRA repair of alma-7b-flap40-gen-multi, ALMA's recipe (RepairSpec defaults). Written by scripts/grid.py repairs.
name: alma-7b-flap40-gen-multi-lora
source: configs/models/alma-7b-flap40-gen-multi.yaml
data: data/calibration/repair-multi-clean
